package com.hokhanh.artist.response.common;

public enum StatusType {
	NO_ROLE_ASSIGNED,
	NO_MUSIC_GENRE_ASSIGNED,
	ARTIST_NOT_FOUND,
	USER_NOT_FOUND,
	USER_REGISTERED,
	NO_COLLABORATOR_ASSIGNED,
	PROJECT_NOT_FOUND,
	YOU_NOT_POSTER,
	SEARCH_YOUR_SELF
}
