eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${EUREKA_PORT:8889}/eureka

spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    http:
      path: /graphql
      
user-service:
  base-url: ${USER_SERVICE_URL:http://user-service}
  
artist-service:
  base-url: ${ARTIST_SERVICE_URL:http://artist-service}