eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8889/eureka

server:
  port: 0
  
spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    http:
      path: /graphql
      
user-service:
  base-url: http://user-service