spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5671}
    virtual-host: ${RABBITMQ_VHOST:/} #này giống như tên database vậy
    
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9201}
    
  data:
    mongodb:
      username: ${MONGODB_USERNAME:hoofkhanh}
      password: ${MONGODB_PASSWORD:hoofkhanh}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27010}
      database: ${MONGODB_DATABABASE:history}
      authentication-database: ${MONGODB_AUTHEN_DB:admin}
    
server:
  port: ${SERVER_PORT:8083}