type RoleResponse{
	id: ID!
	name: String!
}

type ArtistResponse{
	id: ID!
	roles: [RoleResponse!]
	musicGenres: [MusicGenreResponse!]
	birthdate: String!
	gender: Boolean!
	artistName: String!
	residence: String!
	otherRoleNames: String
	otherMusicGenreNames: String
}

type ArtistProfileUpdateResponse{
	artist: ArtistResponse!
	avatarUrl: String!
	instagramUrl: String
	facebookUrl: String
	tiktokUrl: String
	description: String
}

type ArtistRegistrationResponse{
	artist: ArtistResponse!
}

type ArtistSearchResponse{
	artist: ArtistResponse!
	avatarUrl: String!
	avatarCloudinaryPublicId: String
	instagramUrl: String
	facebookUrl: String
	tiktokUrl: String
	description: String
	projects: [ProjectResponse!]
	gpsLocation: GpsLocationResponse!
}

type ArtistRegistrationApiResponse{
	apiResponse: ApiResponse!
	data: ArtistRegistrationResponse
}

type ArtistProfileUpdateApiResponse{
	apiResponse: ApiResponse!
	data: ArtistProfileUpdateResponse
}

type ArtistSearchApiResponse{
	apiResponse: ApiResponse!
	data: ArtistSearchResponse
}

type ArtistPage{
	content: [ArtistResponse!]!
	page: PageInfo!
}

type ArtistListApiResponse{
	success: Boolean!
	message: String!
	statusType: StatusType
	data: ArtistPage!
}