type ArtistSummaryResponse{
	id: ID!
	artistName: String!
	avatarUrl: String
}

type ProjectResponse{
	id: ID!
	poster: ArtistSummaryResponse!
	collaborators: [ArtistSummaryResponse!]
	musicGenres: [MusicGenreResponse!]
	customCollaborators: String
	name: String!
	description: String!
	musicUrl: String!
	musicCloudinaryPublicId: String!
	imageUrl: String!
	imageCloudinaryPublicId: String!
	duration: Float!
	otherMusicGenreNames: String
}

type ProjectCreationResponse{
	project: ProjectResponse! 
}

type ProjectCreationApiResponse{
	apiResponse: ApiResponse!
	data: ProjectCreationResponse
}

type ProjectUpdateResponse{
	project: ProjectResponse! 
}

type ProjectUpdateApiResponse{
	apiResponse: ApiResponse!
	data: ProjectUpdateResponse
}

type ProjectPage{
	content: [ProjectResponse!]!
	page: PageInfo!
}

type ProjectListApiResponse{
	success: Boolean!
	message: String!
	statusType: StatusType
	data: ProjectPage!
}