CREATE TABLE role (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);

INSERT INTO role (name) VALUES 
('PRODUCER'),
('RAPPER'),
('SINGER'),
('COMPOSER'),
('LYRICIST'),
('DJ'),
('INSTRUMENTALIST'),
('MIXING ENGINEER'),
('MASTERING ENGINEER'),
('OTHER')